name = "tvbox-sub"
main = "./worker.js"
compatibility_date = "2024-11-17"

kv_namespaces = [
  { binding = "TVBOX", id = "eb0fd6580e6f46f1950d66a314e0d4c5" }
]

# assets = { directory = "./dist/", binding = "ASSETS" }

